import { describe, it, expect, afterAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { tmpdir } from 'node:os';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';

import {
  renderAgentsMarkdown,
  stripTimestamp,
  runCli,
} from '../../scripts/gen-atelier-agents-md';

const __dirname = dirname(fileURLToPath(import.meta.url));
const AGENTS_MD = join(__dirname, '..', '..', 'AGENTS.md');

const REGISTRY_NAMES = [
  'BuildProgress',
  'ComparisonMatrix',
  'DesignSystemPanel',
  'KPIBoard',
  'MoodBoard',
  'PersonaCard',
  'QuoteCard',
  'Sitemap',
  'TestimonialCard',
];

describe('gen-atelier-agents-md', () => {
  it('renders all 9 components', () => {
    const md = renderAgentsMarkdown('FIXED');
    for (const name of REGISTRY_NAMES) {
      expect(md).toContain(`## ${name}`);
    }
  });

  it('emits header with provenance + warning', () => {
    const md = renderAgentsMarkdown('FIXED');
    expect(md).toContain('AUTO-GENERATED by scripts/gen-atelier-agents-md.ts');
    expect(md).toContain('Source: src/lib/atelier-registry.ts');
    expect(md).toContain('Available components');
  });

  it('lists components alphabetically in the index', () => {
    const md = renderAgentsMarkdown('FIXED');
    const indexBlock = md
      .split('## Available components')[1]
      .split('---')[0]
      .split('\n')
      .filter((l) => l.startsWith('- `'))
      .map((l) => l.match(/^- `([^`]+)`/)?.[1] ?? '');
    expect(indexBlock).toEqual([...indexBlock].sort());
    expect(indexBlock).toHaveLength(9);
  });

  it('is byte-deterministic for the same input (modulo timestamp)', () => {
    const a = stripTimestamp(renderAgentsMarkdown('T1'));
    const b = stripTimestamp(renderAgentsMarkdown('T2'));
    expect(a).toEqual(b);
  });

  it('committed AGENTS.md is up to date (drift gate)', () => {
    expect(existsSync(AGENTS_MD)).toBe(true);
    const onDisk = readFileSync(AGENTS_MD, 'utf-8');
    const fresh = renderAgentsMarkdown();
    expect(stripTimestamp(onDisk)).toEqual(stripTimestamp(fresh));
  });

  it('renders props tables with header row', () => {
    const md = renderAgentsMarkdown();
    expect(md).toMatch(/\| Name \| Type \| Required \| Default \| Description \|/);
  });

  it('emits MDX example fenced blocks per component (9 total)', () => {
    const md = renderAgentsMarkdown();
    const fenceCount = (md.match(/```mdx/g) ?? []).length;
    expect(fenceCount).toBe(9);
  });

  it('stripTimestamp removes the timestamp comment line', () => {
    const md = '<!-- Last generated: 2026-01-01T00:00:00.000Z -->\nBODY';
    expect(stripTimestamp(md)).toBe('BODY');
  });

  it('renders required props as "yes" and optional as "no"', () => {
    const md = renderAgentsMarkdown();
    // PersonaCard.name is required, source is optional.
    expect(md).toMatch(/\| `name` \| `string` \| yes /);
    expect(md).toMatch(/\| `source` \| .* \| no /);
  });

  it('contains the alphabetical first ## section before the last one', () => {
    const md = renderAgentsMarkdown();
    const firstIdx = md.indexOf('## BuildProgress');
    const lastIdx = md.indexOf('## TestimonialCard');
    expect(firstIdx).toBeGreaterThan(0);
    expect(lastIdx).toBeGreaterThan(firstIdx);
  });
});

describe('gen-atelier-agents-md CLI', () => {
  const dir = mkdtempSync(join(tmpdir(), 'agents-md-'));
  const out = join(dir, 'AGENTS.md');

  afterEachCleanup: {
    // teardown registered below
  }

  it('write mode: creates AGENTS.md and returns 0', () => {
    const code = runCli([], out);
    expect(code).toBe(0);
    expect(existsSync(out)).toBe(true);
  });

  it('--check mode: returns 0 when on-disk matches generated', () => {
    runCli([], out);
    const code = runCli(['--check'], out);
    expect(code).toBe(0);
  });

  it('--check mode: returns 1 when AGENTS.md missing', () => {
    const missing = join(dir, 'does-not-exist.md');
    const code = runCli(['--check'], missing);
    expect(code).toBe(1);
  });

  it('--check mode: returns 1 on drift', () => {
    writeFileSync(out, '# drifted content\n', 'utf-8');
    const code = runCli(['--check'], out);
    expect(code).toBe(1);
  });

  afterAll(() => {
    rmSync(dir, { recursive: true, force: true });
  });
});
