import { describe, it, expect, afterAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { tmpdir } from 'node:os';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';

import {
  renderAgentsMarkdown,
  runCli,
} from '../../scripts/gen-atelier-agents-md';

const __dirname = dirname(fileURLToPath(import.meta.url));
const AGENTS_MD = join(__dirname, '..', '..', 'AGENTS.md');

const REGISTRY_NAMES = [
  'BuildProgress',
  'ComparisonMatrix',
  'DesignSystemPanel',
  'KPIBoard',
  'MoodBoard',
  'PersonaCard',
  'QuoteCard',
  'Sitemap',
  'TestimonialCard',
];

describe('gen-atelier-agents-md', () => {
  it('renders all 9 components', () => {
    const md = renderAgentsMarkdown();
    for (const name of REGISTRY_NAMES) {
      expect(md).toContain(`## ${name}`);
    }
  });

  it('emits header with provenance + warning', () => {
    const md = renderAgentsMarkdown();
    expect(md).toContain('AUTO-GENERATED by scripts/gen-atelier-agents-md.ts');
    expect(md).toContain('Source: src/lib/atelier-registry.ts');
    expect(md).toContain('Available components');
  });

  it('header contains NO time-varying content (deterministic drift gate)', () => {
    // The verify-agents-md CI gate uses `git diff --exit-code AGENTS.md`, so
    // every byte of the output must be a pure function of the registry. Any
    // timestamp, git sha, ISO date, or "Last generated" line breaks the gate.
    const md = renderAgentsMarkdown();
    expect(md).not.toMatch(/Last generated/i);
    expect(md).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/); // no ISO timestamps
  });

  it('lists components alphabetically in the index', () => {
    const md = renderAgentsMarkdown();
    const indexBlock = md
      .split('## Available components')[1]
      .split('---')[0]
      .split('\n')
      .filter((l) => l.startsWith('- `'))
      .map((l) => l.match(/^- `([^`]+)`/)?.[1] ?? '');
    expect(indexBlock).toEqual([...indexBlock].sort());
    expect(indexBlock).toHaveLength(9);
  });

  it('is byte-identical across repeated invocations (no time variance)', () => {
    const a = renderAgentsMarkdown();
    const b = renderAgentsMarkdown();
    expect(a).toEqual(b);
  });

  it('committed AGENTS.md is up to date (drift gate)', () => {
    expect(existsSync(AGENTS_MD)).toBe(true);
    const onDisk = readFileSync(AGENTS_MD, 'utf-8');
    const fresh = renderAgentsMarkdown();
    expect(onDisk).toEqual(fresh);
  });

  it('renders props tables with header row', () => {
    const md = renderAgentsMarkdown();
    expect(md).toMatch(/\| Name \| Type \| Required \| Default \| Description \|/);
  });

  it('emits MDX example fenced blocks per component (9 total)', () => {
    const md = renderAgentsMarkdown();
    const fenceCount = (md.match(/```mdx/g) ?? []).length;
    expect(fenceCount).toBe(9);
  });

  it('contains the alphabetical first ## section before the last one', () => {
    const md = renderAgentsMarkdown();
    const firstIdx = md.indexOf('## BuildProgress');
    const lastIdx = md.indexOf('## TestimonialCard');
    expect(firstIdx).toBeGreaterThan(0);
    expect(lastIdx).toBeGreaterThan(firstIdx);
  });
});

describe('gen-atelier-agents-md CLI', () => {
  const dir = mkdtempSync(join(tmpdir(), 'agents-md-'));
  const out = join(dir, 'AGENTS.md');

  it('write mode: creates AGENTS.md and returns 0', () => {
    const code = runCli([], out);
    expect(code).toBe(0);
    expect(existsSync(out)).toBe(true);
  });

  it('--check mode: returns 0 when on-disk matches generated', () => {
    runCli([], out);
    const code = runCli(['--check'], out);
    expect(code).toBe(0);
  });

  it('--check mode: returns 1 when AGENTS.md missing', () => {
    const missing = join(dir, 'does-not-exist.md');
    const code = runCli(['--check'], missing);
    expect(code).toBe(1);
  });

  it('--check mode: returns 1 on drift', () => {
    writeFileSync(out, '# drifted content\n', 'utf-8');
    const code = runCli(['--check'], out);
    expect(code).toBe(1);
  });

  afterAll(() => {
    rmSync(dir, { recursive: true, force: true });
  });
});
