// Bundle-freshness gate (team-lead, iteration 3): `demo/chat-sim.bundle.js` is a committed build
// artifact — R-1 requires `open demo/index.html` to work with NO build step, so the bundle has to
// be checked in, not generated by a dev server. But nothing rebuilds it automatically, and the
// regen command only lived in an HTML comment: anyone who touches `element/**` and forgets to
// re-run it leaves the demo showing stale code — measured against a dirty tree once already
// (team-lead's own words). This test makes that a CI red instead of a silently-stale demo.
//
// Rebuilds element/index.ts to a temp file via the esbuild CLI (a child process, not esbuild's JS
// API — the API's startup check breaks under this suite's jsdom environment/setup.ts, which mock
// `window`; shelling out sidesteps that entirely and matches the regen command exactly, which
// IS the CLI). Byte-compares against the committed file. Positive twin: truncate the freshly
// built temp file before comparing and assert the comparison DOES catch it — an equality check
// that never fails proves nothing (agent-floor.md).

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../../..');
const entry = resolve(here, '../index.ts');
const committedBundlePath = resolve(repoRoot, 'demo/chat-sim.bundle.js');
const esbuildBin = resolve(repoRoot, 'node_modules/.bin/esbuild');

const REGEN_COMMAND =
  'npx esbuild src/components/chat-sim/element/index.ts --bundle --format=iife ' +
  '--global-name=CfChatSim --outfile=demo/chat-sim.bundle.js --target=es2020';

let tmpDir: string;

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'chat-sim-bundle-'));
});
afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

function rebuildBundle(): string {
  const out = join(tmpDir, 'chat-sim.bundle.js');
  execFileSync(esbuildBin, [
    entry,
    '--bundle',
    '--format=iife',
    '--global-name=CfChatSim',
    `--outfile=${out}`,
    '--target=es2020',
  ]);
  return readFileSync(out, 'utf8');
}

describe('demo/chat-sim.bundle.js is fresh (T-002 iteration 3, team-lead)', () => {
  it('matches a fresh rebuild of element/index.ts byte-for-byte', () => {
    const fresh = rebuildBundle();
    const committed = readFileSync(committedBundlePath, 'utf8');
    if (fresh !== committed) {
      throw new Error(
        `demo/chat-sim.bundle.js is STALE relative to src/components/chat-sim/element/**.\n` +
          `Regenerate it with:\n\n  ${REGEN_COMMAND}\n\nthen commit the updated file.`,
      );
    }
    expect(fresh).toBe(committed);
  });

  it('the instrument can go red (positive twin): a truncated fresh build IS caught', () => {
    const fresh = rebuildBundle();
    const truncated = fresh.slice(0, Math.floor(fresh.length / 2));
    const committed = readFileSync(committedBundlePath, 'utf8');
    expect(truncated).not.toBe(committed); // proves the comparison can fail, not just pass
  });
});
