/**
 * Writes the --cf-spring-* tokens into src/styles/index.css from SPRINGS (src/lib/spring.ts),
 * between the GEN:SPRINGS markers. `--check` fails if the CSS drifted from the presets.
 *
 *   npm run gen:springs          # regenerate
 *   npm run verify:springs       # CI / pre-commit drift check
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SPRINGS, springToCSSLinear } from "../src/lib/spring";

const CSS = resolve(import.meta.dirname, "../src/styles/index.css");
const START = "  /* GEN:SPRINGS:START — generated by scripts/gen-spring-tokens.ts, do not edit */";
const END = "  /* GEN:SPRINGS:END */";

export function renderSpringTokens(): string {
  const lines = [START];
  for (const [name, params] of Object.entries(SPRINGS)) {
    const { easing, duration } = springToCSSLinear(params);
    lines.push(`  --cf-spring-${name}: ${easing};`);
    lines.push(`  --cf-spring-${name}-duration: ${Math.round(duration * 1000)}ms;`);
  }
  lines.push(END);
  return lines.join("\n");
}

function main() {
  const css = readFileSync(CSS, "utf8");
  const a = css.indexOf(START);
  const b = css.indexOf(END);
  if (a === -1 || b === -1) throw new Error(`GEN:SPRINGS markers not found in ${CSS}`);
  const next = css.slice(0, a) + renderSpringTokens() + css.slice(b + END.length);
  if (process.argv.includes("--check")) {
    if (next !== css) {
      console.error("✗ --cf-spring-* tokens drifted from SPRINGS. Run: npm run gen:springs");
      process.exit(1);
    }
    console.log("✓ spring tokens in sync");
    return;
  }
  writeFileSync(CSS, next);
  console.log("✓ wrote --cf-spring-* tokens");
}

main();
